Repository TOMO-YOSHI/mokumoku, pull requests merged in 2022-10, with the labels that each got.

#22 define db schema in schema.prisma file and change the order fo instal…
  README.md
  prisma/client.ts
  prisma/description.md
  prisma/migrations/20220929040437_init/migration.sql
  prisma/migrations/20220929041426_init/migration.sql
  prisma/migrations/20221007051411_created_custom_composite/migration.sql
  prisma/migrations/20221007054558_update_user_model/migration.sql
  prisma/migrations/20221008042407_update_venue_length/migration.sql
  prisma/migrations/20221010024529_update_entity_name/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  prisma/sql_utils.ts
  tsconfig.json
Labels: documentation, enhancement

#26 Updated the getUser query
  README.md
  pages/api/resolvers/index.ts
  pages/api/resolvers/query/getEvents.ts
Labels: enhancement

#25 Feature install apolloclient
  components/TestClient.tsx
  lib/apollo.ts
  package.json
  pages/_app.page.tsx
  pages/index.page.tsx
  yarn.lock
Labels: install plugins

#28 edit readme to add instructions about codegen
  README.backup.md
  README.md
Labels: documentation
